version: '3.7'

services:
  my_todo:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    expose:
      - "8000"
  nginx:
    build: ./Nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - my_todo

volumes:
  static:

